image: cirrusci/flutter

pipelines:
  branches:
    masternew:
      - step:
          name: Build APK
          script:
            - flutter clean
            - flutter pub get
            - flutter --no-color build apk
          artifacts:
            - build/app/outputs/apk/release/app-release.apk
      